### ISSUE TITLE
Requirements.txt NOT FOUND

### ISSUE THREAD

**Issue by ryuuzake** [Shivelight/kaskus-py#1]
Please push some requirements.txt so it will be easy for someone to install it from pip

or

I see you're using setup.py but the required module are still lack of it e.g. Pillow for the extract_pixels.py

**Comment by Shivelight** [comment]
The ``tool`` directory is not part of the module; its purpose is to make it easier to decrypt the ``consumer key`` from the native app.

Having a README on the dir to include more information about what this tool does is not a bad idea.
Let me know if you want to open a pull request.

**Comment by Shivelight** [comment]
I've added some instruction on how to use the tool.

e4365e5ba0a37649744fca87a29ffc190a3ffa60
