### ISSUE TITLE
Request Failed - Access Denied

### ISSUE THREAD

**Issue by sluxzer** [Shivelight/kaskus-py#2]
Hi there. 

First, thank you for making this repo, finally found someone who loved to make script for kaskus 👍 

Well, Could you tell me what's wrong with this response: 
{"error":true,"errorcode":110,"errormessage":"Tidak diperkenankan mengakses","errordetails":[{"key":"oauth_problem","rule":"signature_invalid","message":" * }

is it because wrong consumer key & secret or what?
i'd notice the tools just extract consumer key, not the secret.

Thanks.

**Comment by Shivelight** [comment]
I can't believe I miss this issue notification. Anyway, I haven't updated the module for a while since I rarely use it and I started this project to learn something new and don't even think I'll to use it. I'll look up for this issue.

**Comment by Shivelight** [comment]
I've already checked the latest Kaskus native app, and surprisingly they haven't changed the key nor the secret. The only problem I'm facing was outdated User Agent version, bumping the version fixed the problem. I also removed every model class from the library because it was a bad decision, by returning good ol' json it gives developers more flexibility.

**Comment by sluxzer** [comment]
Hello bro,

could you tell me how can i extract the consumer secret? cause the tools you give only extract the key right?

> I've already checked the latest Kaskus native app, and surprisingly they haven't changed the key nor the secret. The only problem I'm facing was outdated User Agent version, bumping the version fixed the problem. I also removed every model class from the library because it was a bad decision, by returning good ol' json it gives developers more flexibility.

**Comment by Shivelight** [comment]
After decompiling the app you can search for the following strings:

     "live"
     "secret : %s"
     "key : %s"
     "https://www.kaskus.co.id/api/oauth/"
     "Kaskus Android App %s"

The secret should be close to those strings.

Get Outlook for Android<https://aka.ms/ghei36>

**Comment by sluxzer** [comment]
Hi there, 
Please forgive me for abandon my own request, i think this repo is not active anymore.

Recently i try to run this script again, and facing this issue:
Error Response: 
\kaskus-py\kaskuspy\core.py", line 32, in _get  raise e
kaskuspy.exceptions.ErrorResponse: ErrorResponse(error=True, errorcode=400, errormessage=Silakan update Aplikasi agan, errordetails=None)

It seems they change the key, do you have times to looking this issue? :)

**Comment by Shivelight** [comment]
It is not active but I still maintain the project for fix and update. I'll look into it.

**Comment by sluxzer** [comment]
> It is not active but I still maintain the project for fix and update. I'll look into it.

Wooh, it was fast then before hehe, i'm glad you still active looking this repo 👍 

looking forward for the update then, thanks.

**Comment by Shivelight** [comment]
I'll start working on the update either tonight or tomorrow night.

**Comment by sluxzer** [comment]
> I'll start working on the update either tonight or tomorrow night.

i'll patiently wait for the update :)

**Comment by Shivelight** [comment]
Please try the latest commit, I also pushed the fix to PyPI.

**Comment by sluxzer** [comment]
> Please try the latest commit, I also pushed the fix to PyPI.

such a news, i already try the latest commit, and it's working legit.  👍 

Thank you so much bro, now i could close this ticket since 2018 haha
